### ISSUE TITLE
res.success is TRUE when test run fails

### ISSUE THREAD

**Issue by ChrisBland** [jsforce/jsforce-metadata-tools#1]
I'm using gulp-jsforce-deploy to build an automated deployment process.
If i use the following config to deploy:
{
        username: process.env.SF_USERNAME,
        password: process.env.SF_PASSWORD+process.env.SF_TOKEN,
        loginUrl: process.env.LOGIN_URL,
        pollInterval: 10*1000,
        pollTimeout: 3600000,
        checkOnly: true,
        testLevel: ['RunLocalTests']
 }

The reportDeployResult method sets res.success = TRUE if Number Test Errors >= 1. Is that the expected behavior? I'll submit a PR, just let me know how you would like it to be configured.

**Comment by stomita** [comment]
The status of deployment result is only showing there is no invalid metadata definitions to complete the deployment, not the code is running without test failure. Set `rollbackOnError` option if you want to fail the deployment when there are any errors in tests.
