### ISSUE TITLE
Error "invalid distance too far back" retrieving Static Resources metadata

### ISSUE THREAD

**Issue by gabrielmoreira** [jsforce/jsforce-metadata-tools#6]
Hi,
im getting error `invalid distance too far back` using `jsforce-retrieve` for `--memberTypes StaticResource:*`

```
Logged in as: root-abc@abc.com.br
Retrieving from server...

Retrieve Succeeded.

Id: 09S36000008gBCJE99
Status: Succeeded
Success: true
Done: true

Extracting:  src/staticresources/xxxx.resource
Extracting:  src/staticresources/xxxx.resource-meta.xml
Extracting:  src/staticresources/yyyy.resource
Extracting:  src/staticresources/yyyy.resource-meta.xml
Extracting:  src/staticresources/zzzz.resource
Extracting:  src/assets/images/._avatar3.jpg

  Error: invalid distance too far back
```

I think it can be similar to this bug:

https://github.com/joeferraro/MavensMate-Atom/issues/108

**Comment by boxfoot** [comment]
This is a known problem with the unzip library used in this project:  https://github.com/EvanOxfeld/node-unzip/issues/60

@stomita not clear if this project is under active development.  Would you be open to swapping in a different unzip engine, or accepting a PR to do that?

**Comment by stomita** [comment]
@boxfoot if you recommend other zip engine that can work please give me the PR.

**Comment by boxfoot** [comment]
@stomita PR submitted.  Please check it out.  If this works for you, it would be great if you could accept the PR and publish a new npm version.  And let me know if edits are needed.

Much appreciated!
